package de.bno.mindrobot.gui;

public enum Insert {

	WENN_DANN_SONST, SOLANGE_WIE, WIEDERHOLE_X, LINKS, RECHTS, VORWAERTS, RUECKWAERTS, RANDOM_Q, ZIELFELD_Q, VERWIRRT_Q, HINDERNIS_Q, SETZE_GESCHWINDIGKEIT;

}
